apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedemoapp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kubedemoapp
  template:
    metadata:
      labels:
        app: kubedemoapp
    spec:
      containers:
        - name: kubedemoapp
          image: tejashwini1108/week9:t2
          ports:
            - containerPort:Â 5000
